### ISSUE TITLE
Step "I am logged in with credentials:" returns false negative result 

### ISSUE THREAD

**Issue by eryomenkoolya** [BR0kEN-/TqExtension#12]
url - http://cibox03.m3.propeople.com.ua/demo/user/login

The following step do successful login into Drupal admin and after that returns an exception "Failed to login as a user "admin" with password "propeople". 

Given I am logged in with credentials:
      | username | admin     |
      | password | propeople |

screen - http://screencast.com/t/w3BCTPak6UJ

**Comment by BR0kEN-** [comment]
@eryomenkoolya, tests were run on CIBox environment?

**Comment by eryomenkoolya** [comment]
@BR0kEN- on blk
