### ISSUE TITLE
Given I am logged in as a user with "<string>" role, in Features Outlines

### ISSUE THREAD

**Issue by Eftimitac** [BR0kEN-/TqExtension#4]
Features Outline, step >> Given I am logged in as a user with "<string>" role 
fails to create a new user on a second lap and uses credentials for a user which was created and deleted on a first cycle 
Please review screenshot 

> > https://goo.gl/gQhx87

**Comment by BR0kEN-** [comment]
@Eftimitac, I've created a commit (1f89cf125d649679c28b19218672af61ce6ed565) which is allow you to use the following:

``` gherkin
@api @d7
Feature: Test
  Scenario Outline: Test outline
    Given I am logged in as a user with "authenticated user" role
    Then I am log out

    Examples:
      | variable |
      | 1        |
      | 2        |
      | 3        |
```

Please, have a look at the log out step. I'm not sure that inside of outline we need logout a user programmatically. But, in another case, this will trigger an error...

**Comment by BR0kEN-** [comment]
The last one commit (8ee2fd09429edef56c5a39408923def49feebd76) should fix the problem.

@Eftimitac, please use TqExtension of `dev-master` version in `composer.json` and let me know about results.
